[package]
name = "render-opengraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
raqote = { version = "0.8.1", features = [], default-features = false }
fontdue = "0.7.2"
num-traits = "0.2.15"
hex-literal = "0.3.4"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
hex = "0.4.3"
png = "0.17.6"
anyhow = "1.0.65"
graphql_client = "0.11.0"
wasm-bindgen = "0.2.83"
euclid = "0.22.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }


[dev-dependencies]
wasm-pack = "0.10.3"

