service: lambdas

plugins:
  - serverless-esbuild

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  deploymentMethod: direct

functions:
  loadSnapshotVotes:
    role: FetchSnapshotExecutionRole
    name: 'load-snapshot-votes'
    handler: src/lambdas/loadSnapshotVotes/handler.run
    memorySize: 2048
    timeout: 300
    environment:
      S3_BUCKET: ${ssm:loadSnapshotVotes/s3Bucket}
    events:
      - schedule: rate(1 hour)

  ingestUpdatesFromChain:
    role: IngestUpdatesFromChainExecutionRole
    name: 'ingest-updates-from-chain'
    handler: src/lambdas/ingestUpdatesFromChain/handler.run
    memorySize: 2048
    timeout: 600
    environment:
      S3_BUCKET: ${ssm:ingestUpdatesFromChain/s3Bucket}
    events:
      - schedule: rate(15 minutes)

custom:
  esbuild:
    packager: yarn
