name = "ens-agora"
compatibility_date = "2022-09-04"
main = "dist/worker.js"
account_id = "86fdf8ef811b4d0aa8954fa036684ea3"

[env.dev]
name = "ens-agora-dev"
vars = { ENVIRONMENT = "dev", DEPLOYMENT = "ens", HONEYCOMB_DATASET = "nouns-agora-dev" }
kv_namespaces = [
    { binding = "EMAILS", id = "3f6b396c85d3466694256f8fc559eda6" },
    { binding = "INDEXER", id = "7796f7072cfb42389cd522af402adcd2" }
]

[env.staging]
name = "ens-agora-staging"
vars = { ENVIRONMENT = "staging", DEPLOYMENT = "ens", HONEYCOMB_DATASET = "nouns-agora-staging" }
kv_namespaces = [
    { binding = "EMAILS", id = "1d3235287dea476fbe19571e2e4d85a5" },
    { binding = "INDEXER", id = "fb3a66f73ad64440b0c5412e5ca59985" }
]

[env.prod]
name = "ens-agora-prod"
vars = { ENVIRONMENT = "prod", DEPLOYMENT = "ens", HONEYCOMB_DATASET = "nouns-agora-prod" }
account_id = "d0222542a05849995856d260759717d4"
kv_namespaces = [
    { binding = "EMAILS", id = "37d5178587d9482398244f2686fc5476" },
    { binding = "INDEXER", id = "67acb2ceccb847c59dd72d40bf5e710b" }
]

[build]
command = "yarn build-worker"

[site]
bucket = "../frontend/build"

[triggers]
crons = ["0 * * * *"]
