compatibility_date = "2022-11-30"
main = "dist/worker.js"
logpush = true

[env.dev]
name = "optimism-agora-dev"
account_id = "86fdf8ef811b4d0aa8954fa036684ea3"
kv_namespaces = [
    { binding = "EMAILS", id = "23588c86ba844b2ab1e966da7e039f61", preview_id = "23588c86ba844b2ab1e966da7e039f61" }
]
durable_objects.bindings = [
    { name = "STORAGE_OBJECT", class_name = "StorageDurableObjectV1" }
]
analytics_engine_datasets = [
    { binding = "STORAGE_ANALYTICS" }
]

[env.dev.vars]
ENVIRONMENT = "dev"
DEPLOYMENT = "optimism"
HONEYCOMB_DATASET = "nouns-agora-dev"
ADMIN_API_KEY = ''
PRIMARY_DURABLE_OBJECT_INSTANCE_NAME = 'stable5'
BLOCK_STEP_SIZE = "100"
ALLOW_READS_PERCENTAGE = "100"

[env.prod]
name = "optimism-agora-prod"
account_id = "d0222542a05849995856d260759717d4"
kv_namespaces = [
    { binding = "EMAILS", id = "7e78791e33d044f99fe92b52ced1f774" },
]
durable_objects.bindings = [
    { name = "STORAGE_OBJECT", class_name = "StorageDurableObjectV1" }
]
analytics_engine_datasets = [
    { binding = "STORAGE_ANALYTICS" }
]

[env.prod.vars]
ENVIRONMENT = "prod"
DEPLOYMENT = "optimism"
HONEYCOMB_DATASET = "nouns-agora-prod"
PRIMARY_DURABLE_OBJECT_INSTANCE_NAME = 'stable9'
BLOCK_STEP_SIZE = "100"
ALLOW_READS_PERCENTAGE = "100"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StorageDurableObjectV1"]

[build]
command = "yarn build-worker"

[site]
bucket = "../frontend/build"
